# Generated by Django 3.2 on 2021-05-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0003_auto_20210422_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('pickup_method', models.IntegerField(choices=[(1, 'delivery to the beach'), (2, 'pick-up at the bar')])),
                ('delivery_method', models.IntegerField(choices=[(1, 'Beach_point_1'), (2, 'Beach_point_2'), (3, 'Beach_point_3'), (4, 'Beach_point_4'), (5, 'Beach_point_5'), (6, 'Beach_point_6'), (7, 'customer_address')])),
                ('payment_method', models.IntegerField(choices=[(1, 'CASH'), (2, 'BLIK'), (3, 'CARD'), (4, 'TRANSFER')])),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza_shop.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pizza_shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(through='pizza_shop.ProductQuantity', to='pizza_shop.Product'),
        ),
    ]
