# Generated by Django 3.2 on 2021-05-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0005_auto_20210507_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_method',
            new_name='delivery_point',
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='JanKowal', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='house_nr',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=123, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'CASH'), (2, 'BLIK'), (3, 'CARD')]),
        ),
    ]
