# Generated by Django 3.2 on 2021-05-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0007_auto_20210514_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Komentarz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[('Gotówka', 'CASH'), ('BLIK', 'BLIK'), ('Karta', 'CARD')]),
        ),
    ]
