# Generated by Django 3.2 on 2021-06-10 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_shop', '0008_auto_20210520_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Miejscowość'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(max_length=64, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_point',
            field=models.IntegerField(choices=[(1, 'Wejście na plażę nr 1'), (2, 'Wejście na plażę nr 2'), (3, 'Wejście na plażę nr 3'), (4, 'Wejście na plażę nr 4'), (5, 'Wejście na plażę nr 5'), (6, 'Wejście na plażę nr 6'), (7, 'Pod wskazany adres')], verbose_name='Punkt dostawy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='house_nr',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nr'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.IntegerField(choices=[(1, 'Gotówka'), (2, 'Blik'), (3, 'Karta')], verbose_name='Sposób płatności'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=64, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_method',
            field=models.IntegerField(choices=[(1, 'Dowóz'), (2, 'Odbiór własny'), (2, 'Zjem na miejscu')], verbose_name='Rodzaj odbioru'),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='order',
            name='street',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Ulica'),
        ),
    ]
